# Generated by Django 2.2.5 on 2019-10-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=60)),
                ('comuna', models.CharField(blank=True, max_length=5)),
                ('region', models.CharField(blank=True, max_length=2)),
                ('fono_apod', models.CharField(blank=True, max_length=12, verbose_name='Fono Cuidador')),
                ('fono2_apod', models.CharField(blank=True, max_length=12, verbose_name='Fono2 Cuidador')),
                ('parentezco', models.CharField(blank=True, max_length=50)),
                ('correo', models.CharField(blank=True, max_length=40)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Apoderado',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cuidadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=80)),
                ('fe_ini', models.DateTimeField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=60)),
                ('comuna', models.CharField(blank=True, max_length=5)),
                ('region', models.CharField(blank=True, max_length=2)),
                ('fono_cuid', models.CharField(blank=True, max_length=12, verbose_name='Fono Cuidador')),
                ('fono2_cuid', models.CharField(blank=True, max_length=12, verbose_name='Fono2 Cuidador')),
                ('fe_nac', models.DateTimeField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1)),
                ('correo', models.CharField(blank=True, max_length=40)),
                ('notas', models.TextField(blank=True)),
                ('tipo', models.CharField(blank=True, max_length=1)),
                ('media', models.FileField(blank=True, default='', upload_to='fotos/')),
                ('clasi', models.CharField(blank=True, max_length=1)),
                ('extran', models.BooleanField(blank=True, default=0)),
                ('estado', models.BooleanField(blank=True, default=0)),
                ('instr', models.CharField(blank=True, max_length=1)),
                ('elim_foto', models.CharField(blank=True, max_length=1)),
            ],
            options={
                'verbose_name': 'Cuidadore',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre Paciente')),
                ('fe_ini', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('direccion', models.CharField(max_length=61)),
                ('comuna', models.CharField(max_length=5)),
                ('region', models.CharField(max_length=2)),
                ('fono_pcte', models.CharField(blank=True, max_length=12, verbose_name='Fono del Paciente')),
                ('fono2_pcte', models.CharField(blank=True, max_length=12, verbose_name='Fono alternativo del Paciente')),
                ('fe_nac', models.DateTimeField(blank=True, null=True)),
                ('sexo', models.CharField(default=3, max_length=1)),
                ('correo', models.CharField(blank=True, max_length=40)),
                ('n_apod', models.CharField(max_length=80, verbose_name='Nombre Apoderado')),
                ('rut_apod', models.CharField(max_length=10)),
                ('dir_apod', models.CharField(blank=True, max_length=61, null=True)),
                ('f_apod', models.CharField(max_length=12)),
                ('fono2_apod', models.CharField(blank=True, max_length=12, null=True)),
                ('parentes', models.CharField(blank=True, max_length=30, null=True)),
                ('medico', models.CharField(max_length=60)),
                ('correo_apod', models.CharField(blank=True, max_length=40, null=True)),
                ('notas', models.TextField(blank=True)),
                ('cob', models.CharField(max_length=1, null=True)),
                ('estado', models.BooleanField(blank=True, default=0)),
                ('clasi', models.CharField(blank=True, max_length=1)),
                ('abon', models.CharField(blank=True, max_length=1)),
            ],
            options={
                'verbose_name': 'Paciente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=5)),
                ('codigo', models.CharField(blank=True, max_length=5)),
                ('descrip', models.CharField(max_length=79, null=True, verbose_name='Desripcion')),
                ('valor1', models.IntegerField(blank=True)),
                ('valor2', models.IntegerField(blank=True)),
                ('valor3', models.IntegerField(blank=True)),
                ('sw_1', models.IntegerField(blank=True)),
                ('sw_2', models.IntegerField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('corr', models.IntegerField(blank=True)),
                ('fecha2', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Parametro',
                'ordering': ['tipo', 'descrip'],
            },
        ),
    ]
