# Generated by Django 2.2.5 on 2019-11-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detapauta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('paciente', models.CharField(max_length=60, null=True, verbose_name='Nombre Paciente')),
                ('fecha', models.DateTimeField(blank=True, verbose_name='Fecha Pauta')),
                ('valor_t1', models.IntegerField(blank=True)),
                ('tipo_turno1', models.CharField(blank=True, max_length=1)),
                ('valor_t2', models.IntegerField(blank=True)),
                ('tipo_turno2', models.CharField(blank=True, max_length=1)),
                ('valor_t3', models.IntegerField(blank=True)),
                ('tipo_turno3', models.CharField(blank=True, max_length=1)),
                ('total', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'detapauta',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Resupauta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=10)),
                ('nombre', models.CharField(max_length=80, null=True, verbose_name='Nombre Cuidador')),
                ('mes', models.CharField(blank=True, max_length=2)),
                ('ano', models.CharField(blank=True, max_length=4)),
                ('tot_t1', models.IntegerField(blank=True)),
                ('tot_t2', models.IntegerField(blank=True)),
                ('tot_t3', models.IntegerField(blank=True)),
                ('tot_val', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'resupauta',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='cuidadores',
            options={'ordering': ['nombre'], 'verbose_name': 'Cuidadores'},
        ),
        migrations.AddField(
            model_name='cuidadores',
            name='apago1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cuidadores',
            name='apago2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cuidadores',
            name='apago3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='doc_cobro',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pauta',
            name='tipo_turno1',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pauta',
            name='tipo_turno2',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pauta',
            name='tipo_turno3',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='estado',
            field=models.BooleanField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='media',
            field=models.FileField(blank=True, default='', upload_to='misitio/ai/static/img/'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='estado',
            field=models.BooleanField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='fe_ini',
            field=models.DateTimeField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='medico',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
