# Generated by Django 2.2.5 on 2020-02-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otrospermisos',
            options={'permissions': (('menu_pauta', 'menu_pauta'), ('menu_parametros', 'menu_parametros'), ('menu_impresos', 'menu_impresos'))},
        ),
    ]
