# Generated by Django 2.2.5 on 2020-02-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_auto_20200216_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otrospermisos',
            options={'permissions': (('menu_pauta', 'menu_pauta'), ('menu_parametros', 'menu_parametros'), ('menu_impresos', 'menu_impresos'), ('menu_cuidadores', 'menu_cuidadores'), ('menu_pacientes', 'menu_pacientes'), ('menu_apoderados', 'menu_apoderados'), ('nuevo_cuidadores', 'nuevo_cuidadores'))},
        ),
    ]
