# Generated by Django 2.2.5 on 2020-02-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_auto_20200220_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otrospermisos',
            options={'permissions': (('menu_pauta', 'menu_pauta'), ('menu_parametros', 'menu_parametros'), ('menu_impresos', 'menu_impresos'), ('menu_cuidadores', 'menu_cuidadores'), ('menu_pacientes', 'menu_pacientes'), ('menu_apoderados', 'menu_apoderados'), ('nuevo_cuidadores', 'nuevo_cuidadores'), ('elimina_cuidadores', 'elimina_cuidadores'), ('fichacui_aceptar', 'fichacui_aceptar'), ('grid_pctesnuevo', 'grid_pctesnuevo'), ('grid_pcteselimina', 'grid_pcteselimina'), ('fichapcte_aceptar', 'fichapcte_aceptar'), ('fichanticipos_aceptar', 'fichanticipos_aceptar'), ('gridapod_nuevo', 'gridapod_nuevo'), ('gridapod_elimina', 'gridapod_elimina'), ('fichapod_aceptar', 'fichapod_aceptar'))},
        ),
    ]
