# Generated by Django 2.2.5 on 2020-02-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_auto_20200220_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='cheque',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
