# Generated by Django 2.2.5 on 2020-02-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_pacientes_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='banco',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
