# Generated by Django 2.2.5 on 2020-02-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_pacientes_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='fe_ini',
            field=models.DateTimeField(blank=True, verbose_name='Fecha de Inicio'),
        ),
    ]
