# Generated by Django 2.2.5 on 2020-02-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_auto_20200223_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='fe_ini',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
