# Generated by Django 2.2.5 on 2020-02-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_auto_20200223_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='fe_ini',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
