# Generated by Django 2.2.5 on 2020-02-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_auto_20200223_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='fecha_cheque',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='banco',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
