# Generated by Django 2.2.5 on 2020-02-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_auto_20200223_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticipos',
            name='sw_abono',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='abono_inicial',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
