# Generated by Django 2.2.5 on 2020-02-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0013_auto_20200226_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='fe_ini',
            field=models.DateTimeField(default='', verbose_name='Fecha de Inicio'),
        ),
    ]
