# Generated by Django 2.2.5 on 2020-02-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0014_auto_20200226_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes_aux',
            name='fe_ini',
            field=models.DateTimeField(default='', verbose_name='Fecha de Inicio'),
        ),
    ]
