# Generated by Django 2.2.5 on 2020-03-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0016_auto_20200301_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='saldoant',
        ),
        migrations.AlterField(
            model_name='cuidadores',
            name='media',
            field=models.FileField(blank=True, default='', upload_to='misitio/ai/static/img/fotos/'),
        ),
    ]
